name: Build Inex Executable
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ gitea.actor }}
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    # - run: pyinstaller --noconfirm --onefile --console "${{ gitea.workspace }}/inex.py"
    - run: ls ${{ gitea.workspace }}
    - uses: actions/upload-artifact@v4
      with:
        name: Inex
        path: ${{ gitea.workspace }}/output/inex.exe