name: Build Inex Executable
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: pyinstaller --noconfirm --onefile --console "/workspace/jblu/Inex/inex.py"
    - uses: actions/upload-artifact@v4
      with:
        name: Inex
        path: /workspace/jblu/Inex/output/inex.exe